name = "Cteate Aeronautics Pack"
author = "ancApple"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b28ba4e6b193d5ea3f7f6c835e01dcaf6875d30111bc5bf1e16cf664fb92187"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
