name = "Cteate Aeronautics Pack"
author = "ancApple"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "056d49ca8936d34e2b976d598a6a8e3ee20d3c79e569b2d9a3fcab335bf9652f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
