name = "Cteate Aeronautics Pack"
author = "ancApple"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9493d13cac452b27f913f8ea18d30faca10ba01b35458fac99ee256c4bb31077"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
